version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "rowbotony"
    assignees:
      - "rowbotony"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    # Group minor and patch updates
    groups:
      go-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "rowbotony"
    assignees:
      - "rowbotony"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
  
  # Git submodules (test fixtures)
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "1"
      time: "09:00"
    open-pull-requests-limit: 2
    reviewers:
      - "rowbotony"
    assignees:
      - "rowbotony"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "submodules"
